dataset_path: jasonzhango/SPAR-Bench-Tiny
# dataset_path: /SSD_DISK/xx/SPAR-Bench-Tiny
dataset_kwargs:
  token: True
  cache_dir: sparbench_tiny_cache
task: sparbench_tiny
test_split: test
output_type: generate_until
process_docs: !function utils.process_docs
doc_to_visual: !function utils.sparbench_doc_to_visual
doc_to_text: !function utils.sparbench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 100
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.sparbench_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: sparbench_score
    aggregation: !function utils.sparbench_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    mca_post_prompt: "Answer with the option's letter from the given choices directly."
    na_post_prompt: "Please answer the question using a single word or phrase."
  gemini_api:
    pre_prompt: ""
    mca_post_prompt: "Answer with the option's letter from the given choices directly."
    na_post_prompt: "Do not response anything other than a single number!"
  gpt4v:
    pre_prompt: ""
    mca_post_prompt: "Answer with the option's letter from the given choices directly."
    na_post_prompt: "Do not response anything other than a single number!"
metadata:
  - version: 0.0